### ISSUE TITLE
Error: org.openstreetmap.osmosis.core.OsmosisRuntimeException

### ISSUE THREAD

**Issue by rubslopes** [adrianulbona/osm-parquetizer#14]
- Running on Mac OS Ventura 13.2.1, Macbook Air M1.
- apache-maven-3.9.1
- OpenJDK 20

Got the following error:
```
➜ java -jar target/osm-parquetizer-1.0.1-SNAPSHOT.jar massachusetts.pbf

2023-03-24 00:27:16 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-03-24 00:27:16 INFO  CodecPool:153 - Got brand-new compressor [.snappy]
2023-03-24 00:27:16 INFO  CodecPool:153 - Got brand-new compressor [.snappy]
2023-03-24 00:27:16 INFO  CodecPool:153 - Got brand-new compressor [.snappy]
Exception in thread "main" org.openstreetmap.osmosis.core.OsmosisRuntimeException: A PBF decoding worker thread failed, aborting.
	at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfDecoder.sendResultsToSink(PbfDecoder.java:97)
	at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfDecoder.processBlobs(PbfDecoder.java:163)
	at org.openstreetmap.osmosis.pbf2.v0_6.impl.PbfDecoder.run(PbfDecoder.java:175)
	at org.openstreetmap.osmosis.pbf2.v0_6.PbfReader.run(PbfReader.java:115)
	at io.github.adrianulbona.osm.parquet.App.main(App.java:38)
```

**Comment by ciqle** [comment]
Hi @rubslopes , I came across the same issue and confirmed it's due to its dependency on `snappy-java:1.1.7.3`, which is incompatible with Apple Silicon chipsets.
You can download this repo and change `parquet.version` to `1.13.1` and `hadoop.version` to `3.2.3` in [pom.xml](https://github.com/adrianulbona/osm-parquetizer/blob/master/pom.xml), then rebuild the project. It will then use `snappy-java:1.1.8.3` and fully support Mac machines.
